name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install, build, and test
      run: |
        npm install --only=dev
        npm install firebase-tools
        npm install @vue/cli
        npm run build --if-present
      env:
        CI: true
    - name: deploy
      run: ./node_modules/.bin/firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
